backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: "Header Image", name: image, widget: image }
          - { label: "Header Title", name: title, widget: string }
          - { label: "Header Subtext", name: subheading, widget: string }
          - {
              label: "Intro Sections",
              name: intro,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Body Context, name: content, widget: markdown },
                  { label: Image, name: image, widget: image },
                  {
                    label: Button,
                    name: button,
                    required: false,
                    widget: object,
                    fields:
                      [
                        { label: "Button Text", name: text, widget: string },
                        {
                          label: "Button Link (e.g. /menu)",
                          name: link,
                          widget: string,
                        },
                      ],
                  },
                ],
            }
          - {
              label: "Tiled Sections",
              name: tiles,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Body Context, name: content, widget: markdown },
                  { label: Image, name: image, widget: image },
                ],
            }
      - file: "src/pages/about/index.md"
        label: "About Page"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: Introduction,
              name: introduction,
              widget: string,
              required: false,
            }
          - {
              label: Sections,
              name: sections,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Body Context, name: content, widget: markdown },
                  { label: Image, name: image, widget: image },
                  {
                    label: Button,
                    name: button,
                    required: false,
                    widget: object,
                    fields:
                      [
                        {
                          label: "Button Text",
                          name: text,
                          widget: string,
                          required: false,
                        },
                        {
                          label: "Button Link (e.g. /menu)",
                          name: link,
                          widget: string,
                          required: false,
                        },
                      ],
                  },
                ],
            }
      - file: "src/pages/menu/index.md"
        label: "Menu Page"
        name: "menu"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "menu-page",
            }
          - { label: Heading, name: heading, widget: string }
          - {
              label: Introduction,
              name: introduction,
              widget: markdown,
              required: false,
            }
          - {
              label: "Menu Categories",
              name: categories,
              widget: list,
              fields:
                [
                  { label: "Title", name: categoryTitle, widget: string },
                  {
                    label: "Description",
                    name: categoryDescription,
                    widget: markdown,
                    required: false,
                  },
                  { label: "Image", name: categoryImage, widget: image },
                  {
                    label: "Items",
                    name: categoryItems,
                    widget: list,
                    required: false,
                    fields:
                      [
                        { label: "Name", name: itemName, widget: "string" },
                        {
                          label: "Description",
                          name: itemDescription,
                          widget: string,
                          required: false,
                        },
                        {
                          label: "Price",
                          name: itemPrice,
                          widget: "string",
                          required: false,
                        },
                      ],
                  },
                ],
            }
      - file: "src/pages/events/index.md"
        label: "Events Page"
        name: "events"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "events-page",
            }
          - { label: Heading, name: heading, widget: string }
          - {
              label: Introduction,
              name: introduction,
              widget: markdown,
              required: false,
            }
          - { label: ShowTable, name: showTable, widget: boolean }
          - {
              label: Headers,
              name: headers,
              widget: list,
              fields: [{ label: "Column", name: column, widget: string }],
            }
          - {
              label: Events,
              name: events,
              widget: list,
              fields:
                [
                  { label: "Name", name: name, widget: string },
                  { label: "Date", name: date, widget: string },
                  { label: "Location", name: location, widget: string },
                ],
            }
  - name: "templates"
    label: "Templates"
    files:
      - file: "src/templates/data/address.json"
        extension: json
        format: json
        label: "Address"
        name: "address"
        fields:
          - {
              label: "Address",
              name: "address",
              widget: list,
              fields: [{ label: "Address Line", name: line, widget: string }],
            }
      - file: "src/templates/data/hours.json"
        extension: json
        format: json
        label: "Hours"
        name: "hours"
        fields:
          - {
              label: "Hours List",
              name: "hours",
              widget: list,
              fields:
                [
                  { label: "Day(s)", name: day, widget: string },
                  { label: "Hours", name: time, widget: string },
                ],
            }
      - file: "src/templates/data/contact.json"
        extension: json
        format: json
        label: "Contact Information"
        name: "contact"
        fields:
          - { label: "Email Address", name: "email", widget: string }
          - { label: "Phone Number", name: "phone", widget: string }
      - file: "src/templates/data/flavors.json"
        extension: json
        format: json
        label: "Flavors of the Week (If there are none, just leave the list empty and save)"
        name: "flavors"
        fields:
          - {
              label: "Flavors",
              name: "flavors",
              widget: list,
              required: false,
              fields:
                [
                  {
                    label: "Flavor",
                    name: flavor,
                    widget: string,
                    required: false,
                  },
                ],
            }
